### ISSUE TITLE
jTracert fails to analyze an application with org.jgraph library

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ankit4u3/jtracert#15]
```
What steps will reproduce the problem?
1. Try to analyze attached application with empty class filter
2. Some of the method calls are absent in jTracert GUI
3. If you turn on verbose mode, you'll see an ASM exception

What is the expected output? What do you see instead?
jTracert should work with any 3pp libraries including org.jgraph

Tested on Windows XP 32bit with Sun JRE 1.5
```

Original issue reported on code.google.com by `Dmitry.Bedrin` on 18 Mar 2009 at 9:24

Attachments:
- [ENGR3980U-ProgAss.rar](https://storage.googleapis.com/google-code-attachments/jtracert/issue-15/comment-0/ENGR3980U-ProgAss.rar)

**Comment by GoogleCodeExporter** [comment]
```
It appears that the problem isn't related to jGraph library.

Below is an extract from exception:
        at java.awt.EventDispatchThread.run(Unknown Source)

Caused by: java.lang.IllegalStateException: Unknown local variable 3

        at com.google.code.jTracert.org.objectweb.asm.commons.LocalVariablesSort

er.remap(Unknown Source)

        at com.google.code.jTracert.org.objectweb.asm.commons.LocalVariablesSort

er.visitFrame(Unknown Source)

        at com.google.code.jTracert.org.objectweb.asm.ClassReader.accept(Unknown

 Source)

        at com.google.code.jTracert.org.objectweb.asm.ClassReader.accept(Unknown

 Source)

        at com.google.code.jtracert.instrument.impl.asm.JTracertASMByteCodeTrans

former.transform(JTracertASMByteCodeTransformer.java:37)

        ... 45 more

java.lang.instrument.IllegalClassFormatException: Failed to transform bytecode o

f class Parser

        at com.google.code.jtracert.agent.JTracertClassFileTransformer.transform

(JTracertClassFileTransformer.java:113)

        at sun.instrument.TransformerManager.transform(Unknown Source)

        at sun.instrument.InstrumentationImpl.transform(Unknown Source)

        at java.lang.ClassLoader.defineClass1(Native Method)

        at java.lang.ClassLoader.defineClass(Unknown Source)

        at java.security.SecureClassLoader.defineClass(Unknown Source)

        at java.net.URLClassLoader.defineClass(Unknown Source)

        at java.net.URLClassLoader.access$000(Unknown Source)
```

Original comment by `Dmitry.Bedrin` on 19 Mar 2009 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
Fixed in SVN revision r245
```

Original comment by `Dmitry.Bedrin` on 27 Mar 2009 at 12:47
- Changed state: **Fixed**
