### ISSUE TITLE
jTracert fails to analyze jTracert-0.1.2-setup.jar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ankit4u3/jtracert#16]
```
What steps will reproduce the problem?
1. Start jTracert-0.1.2-setup.jar with jTracert agent
2. Connect to the jTracert agent from jTracert GUI using empty class filter
3. Observer exception in jTracert-0.1.2-setuip.jar output

What is the expected output? What do you see instead?

Application should work fine.

It works actually, but there're exceptions in the application output:

ava.lang.NullPointerException
        at
com.google.code.jtracert.util.ClassUtils.getFullyQualifiedName(ClassUtils.java:1
6)
        at
com.google.code.jtracert.agent.JTracertClassFileTransformer.transform(JTracertCl
assFileTransformer.java:76)
        at
sun.instrument.TransformerManager.transform(TransformerManager.java:169)
        at
sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
        at
com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl$TransletClassLoader.d
efineClass(TemplatesImpl.java:126)
        at
com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.defineTransletClasses
(TemplatesImpl.java:312)
        at
com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.getTransletInstance(T
emplatesImpl.java:349)
        at
com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.newTransformer(Templa
tesImpl.java:382)
        at
com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransform
er(TransformerFactoryImpl.java:615)
        at
com.izforge.izpack.adaptator.impl.XMLParser.parseLineNrFromInputSource(Unknown
Source)
        at com.izforge.izpack.adaptator.impl.XMLParser.parse(Unknown Source)
        at com.izforge.izpack.LocaleDatabase.add(Unknown Source)
        at com.izforge.izpack.LocaleDatabase.<init>(Unknown Source)
        at com.izforge.izpack.installer.GUIInstaller.loadLangPack(Unknown
Source)
        at com.izforge.izpack.installer.GUIInstaller.access$000(Unknown Source)
        at com.izforge.izpack.installer.GUIInstaller$1.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
        at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273
)
        at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
        at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173
)
        at
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
        at
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)



GNU/Linux Mandriva 2008.0
java version "1.6.0_06"
Java(TM) SE Runtime Environment (build 1.6.0_06-b02)
Java HotSpot(TM) Client VM (build 10.0-b22, mixed mode)



```

Original issue reported on code.google.com by `Dmitry.Bedrin` on 26 May 2009 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
We need to support null class names since they're permitted by the
ClassLoader.defineClass method contract
```

Original comment by `Dmitry.Bedrin` on 26 May 2009 at 7:37

**Comment by GoogleCodeExporter** [comment]
```
Reproduced in sample application "xalan":
http://code.google.com/p/jtracert/source/browse/trunk/samples/xalan/
```

Original comment by `Dmitry.Bedrin` on 11 Jun 2009 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
Fixed in SVN revision r329
```

Original comment by `Dmitry.Bedrin` on 11 Jun 2009 at 2:10
- Changed state: **Fixed**
